name: watch_store
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 2. For Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  # 3. For State Management
  provider: ^6.1.2
  shared_preferences: ^2.3.5

  # 4. For Data & API
  http: ^1.2.1
  uuid: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # 5. For Device Capabilities
  connectivity_plus: ^7.0.0
  image_picker: ^1.1.2
  geolocator: ^14.0.2
  battery_plus: ^7.0.0
  firebase_storage: ^13.0.4
  cached_network_image: ^3.4.1
  google_sign_in: ^6.2.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    # Brand logos
    - assets/images/brands/ap.png
    - assets/images/brands/casio.png
    - assets/images/brands/citizen.png
    - assets/images/brands/omega.png
    - assets/images/brands/patek.png
    - assets/images/brands/richard_mille.png
    - assets/images/brands/rolex.png
    - assets/images/brands/seiko.png
    - assets/images/brands/swatch.png
    - assets/images/brands/tag_heuer.png

    # Watch images
    - assets/images/watches/
