name: appcounter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 1. For .env files
  flutter_dotenv: ^5.1.0

  # 2. For Firebase (Criteria 2)
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1

  # 3. For State Management (Criteria 6)
  provider: ^6.1.2

  # 4. For Data & API (Criteria 3)
  http: ^1.2.1
  hive: ^2.2.3 # <-- This is the corrected version
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # 5. For Device Capabilities (Criteria 5)
  connectivity_plus: ^6.0.3
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  battery_plus: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    # Brand logos
    - assets/images/brands/ap.png
    - assets/images/brands/casio.png
    - assets/images/brands/citizen.png
    - assets/images/brands/omega.png
    - assets/images/brands/patek.png
    - assets/images/brands/richard_mille.png
    - assets/images/brands/rolex.png
    - assets/images/brands/seiko.png
    - assets/images/brands/swatch.png
    - assets/images/brands/tag_heuer.png

    # Your .env file
    - .env
    
    # Watch images
    - assets/images/watches/